CREATE TABLE PESSOA (
    ID UUID PRIMARY KEY,
    NOME VARCHAR (168),
    DATA_NASCIMENTO TIMESTAMP,
    STATUS NUMERIC (1)
);

CREATE TABLE GASTO (
    ID UUID PRIMARY KEY,
    PESSOA_ID UUID NOT NULL,
    DESCRICAO VARCHAR(255),
    DATA_PROCESSAMNETO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    VALOR NUMERIC (11,2) NOT NULL,
    TAGS VARCHAR(255),
    FOREIGN KEY (PESSOA_ID) REFERENCES PESSOA(ID)
);
